### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by alphastrata** [TheDude-gh/diablo2graphics#2]
Hiya,

http://diablo.novapolis.net/diablographics/DiabloGraphicsData.zip this link doesn't exist anymore :(
Any chance you could fix it? 

ty

**Comment by TheDude-gh** [comment]
Hi, 
I have removed, probably because I forgot it is linked here on Github. 

The file contained some game TXT/TBL/PAL files.

I am not going to put it there. Instead I will just update notes with files that are needed to be extracted from D2 MPQ archives.
